services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./nextjs-project:/app

    command: npm run dev # 本番用のCMDを開発モードに上書き

    stdin_open: true

    tty: true
